Sprint 13
IBS-PRO/java-shareit pull request #1
Opened 2023-10-29 10:01 UTC by IBS-PRO

2023-10-30 10:55 UTC, YazykovMikhail requested changes

2023-10-30 10:55 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private ItemRequest request;
пока стоит закомментрировать, ведь реквесты еще не реализованы

2023-10-30 10:55 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto updateItem(@PathVariable Long itemId,
Стоит делать разнеы dto для запроса и ответа.
ItemDtoRequest
ItemDtoResponse
к примеру.
потому что поля могут отличаться, например при запросе id не передается, но оно есть в dto.
Поправь везде.

и так же для каждого эндпоинта могут быть свои dto, если контракты отличаются
Например:
CreateItemDtoRequest
CreateItemDtoResponse
UpdateItemDtoRequest
UpdatetemDtoResponse

Если ответы у контроллера все в одно формате, то для ответа достаточно одного dto, но вот запросы обычно бывают все с разынми контарктыми, поэтому стоит сделать для каждого ндпоинта свое dto что бы там не было лишних полей

2023-10-30 10:55 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/storage/UserInMemoryStorage.java
> +    private final Set<String> emails = new HashSet<>();
отлично

2023-10-30 10:55 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/storage/UserInMemoryStorage.java
> +    Long idCounter = 0L;
модификатор доступа

2023-10-30 10:55 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/storage/ItemInMemoryStorage.java
> +    Map<Long, Item> items = new HashMap<>();
бодификатор доступа
final

2023-10-30 10:55 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/storage/ItemInMemoryStorage.java
> +    public Item addItem(Item item, User owner) {
репозиторий рабоатет только со своей моделью, в метод должны приходить уже готовые модули.
Т.е модели подготавливаются на уровне сервиса
public Item add(Item item) {

2023-10-30 10:55 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/storage/ItemInMemoryStorage.java
> +    public Item updateItem(Long itemId, Item item, User owner) {
приходит уже готовая модель

2023-10-30 10:55 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/storage/ItemInMemoryStorage.java
> +        item.setOwner(owner);
устанавливай овнера в сервисе
Этот репозиторий отвечает за итемы, он ничего не должен знать про другие модели

2023-11-11 11:11 UTC, IBS-PRO commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private ItemRequest request;
так без этого ничего работать не будет 😬

2023-11-16 18:32 UTC, merged